spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reservation_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/code212

server:
  port: 8081
