server:
  port: 8082

spring:
  application:
    name: resource-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9999}


# ═══════════════════════════════════════════════════════════
# EUREKA - DIRECTEMENT ICI
# ═══════════════════════════════════════════════════════════
#eureka:
#  client:
#    service-url:
#      defaultZone: http://discovery-service:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html